version: '3'
services:
    php-server:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: php-dev-server
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:80'
        environment:
            WWWUSER: '${WWWUSER}'
            DEV_ENVIRONMENT: 1
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
            PHP_IDE_CONFIG: '${XDEBUG_PHP_IDE_CONFIG:-serverName=localhost}'
        volumes:
            - '.:/var/www/html'

